
// referred from www.verificationguide.com but s comments generated by my brain
//Basically when u shallow copy stuff(properties and methods) from one object to another,all varaiables and methods gets copied but if the class has child classes
//those wont get new memory allocated, both the copies would be pointing to the same subclass stuff.
//-- class ---   
class address_range;           //a class
  bit [31:0] start_address;   //with properties
  bit [31:0] end_address  ;
  
  function new();            //and a method
    start_address = 10;
    end_address   = 50;
  endfunction
endclass

//-- class ---    
class packet;             //another class
  
  //class properties
  bit [31:0] addr;        //with properties 
  bit [31:0] data;        
  address_range ar;       //here the class address_range, gets a handle named ar
  
  //constructor
  function new();        //its custom new function which initilaizes some datas and creates an object using the handle ar
    addr  = 32'h10;
    data  = 32'hFF;
    ar = new(); //creating object 
  endfunction
  
  //method to display class prperties
  function void display();    //another function that displays stuff
    $display("---------------------------------------------------------");
    $display("\t addr  = %0h",addr);                      //from the class properties
    $display("\t data  = %0h",data);
    $display("\t start_address  = %0d",ar.start_address);  //aswell as stuff from the new object
    $display("\t end_address  = %0d",ar.end_address);
    $display("---------------------------------------------------------");
  endfunction
  
endclass

// -- module ---        //NOW THE MODULE STARTS
module class_assignment;
  packet pkt_1;           //we got 2 handles for the class packet
  packet pkt_2;

  initial begin
    
    pkt_1 = new();       //creating pkt_1 object
    $display("\t****  calling pkt_1 display  ****");
    pkt_1.display();
    
    pkt_2 = new pkt_1;   //creating pkt_2 object and shallow copying pkt_1 to pkt_2
    $display("\t****  calling pkt_2 display  ****");
    pkt_2.display();  
    
                         //changing values with pkt_2 handle
    pkt_2.addr = 32'h68;
    pkt_2.ar.start_address = 60;
    pkt_2.ar.end_address = 80;
    $display("\t****  calling pkt_1 display after changing pkt_2 properties ****");
    //changes made to pkt_2.ar properties reflected on pkt_1.ar, so only handle of the object get copied, this is called shallow copy 
    pkt_1.display();
    $display("\t****  calling pkt_2 display after changing pkt_2 properties ****");
    pkt_2.display(); 
  end
  
endmodule
